### ISSUE TITLE
Nginx reverse proxy for frontend

### ISSUE THREAD

**Issue by galbwe** [codeforkansascity/meep#55] opened 2019-06-02 17:09 UTC
See [this blog post](https://medium.com/yld-engineering-blog/deploy-your-create-react-app-with-docker-and-ngnix-653e94ffb537).

**Comment by Spechal** [comment] 2019-06-10 19:54
I can take this

**Comment by Spechal** [comment] 2019-06-18 12:24
Duplicate of #46

**Closed** 2019-06-18 12:24 UTC
Labels: Dev ops, Docker, Nginx
