### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by galbwe** [codeforkansascity/meep#46] opened 2019-05-13 22:39 UTC
Make a Dockerfile to build an image and run the frontend in a container.

**Comment by clementkng** [comment] 2019-06-09 05:26
Hi @galbwe I'm interested in trying this issue, but since I'm new to docker, I'm not sure where to start. Any tips for starting off?

**Comment by galbwe** [comment] 2019-06-09 15:45
@clementkng some work has already been done on this in a (docker compose)[https://github.com/codeforkansascity/meep/pull/54] PR. If you want to review and suggest possible improvements, that would be awesome. I think we still need to configure the nginx server (in meep-backend) as a reverse proxy for the react app, or set up another nginx server just for react. I'm not sure how serving static content from nginx is going to work with react yet, especially if we're using styled-components. 

Here are some resources I found helpful:

Docker docs:
https://docs.docker.com/get-started/
https://docs.docker.com/engine/reference/builder/

this tutorial https://mherman.org/blog/dockerizing-a-react-app/

webpack docs: https://webpack.js.org/concepts

nginx docs: https://docs.nginx.com/nginx/

I know this is a lot of stuff. Feel free to ask questions, either here or in the slack channel.

**Comment by josiah14** [comment] 2019-06-10 18:40
I can probably assist some with this work, as well.  I have decent experience with containerization.

**Comment by clementkng** [comment] 2019-06-10 20:10
Hi @josiah14 if it's not too inconvenient, do you mind suggesting what can be improved in this PR that's accessible for a beginner to docker? Also, I'd be down to work together on this if you're free at some point.

**Comment by clementkng** [comment] 2019-06-10 20:10
Hi @josiah14 if it's not too inconvenient, do you mind suggesting what can be improved in this PR that's accessible for a beginner to docker? Also, I'd be down to work together on this if you're free at some point.

**Comment by Spechal** [comment] 2019-06-18 12:23
Duplicate of #55 ?

**Comment by Spechal** [comment] 2019-08-15 21:52
Closing -- gh-55 merged

**Closed by Spechal** 2019-08-15 21:52 UTC
